### ISSUE TITLE
Fix from issue #5227 causing Microsoft Office (MSO) ghost tables in email template

### ISSUE THREAD

**Issue by duardo56** [SparkDevNetwork/Rock#5288]
### Prerequisites ###

Put an X between the brackets on this line if you have done all of the following:

* [x] Did you perform a search at https://github.com/issues?q=is%3Aissue+user%3ASparkDevNetwork+-repo%3ARock to see if your bug or enhancement is already reported?
 ~~Can you reproduce the problem on a fresh install or the [demo site](http://rock.rocksolidchurchdemo.com/)?~~ **Cannot test in demo site**
* [x] Did you include your Rock version number and [client culture ](httXps://github.com/SparkDevNetwork/Rock/wiki/Environment-and-Diagnostics-Information) setting?

#### A Picture Is worth a Thousand Words ####

![Github Report](https://user-images.githubusercontent.com/16809768/213887442-4c17cac0-cada-4653-b1d0-bfada2b31077.jpg)

### Description ###

After applying fix from issue #5227, some pasted content from paste to word box will generate MSO ghost table content on some email that are sent out from email wizard. 

Not all emails will contain ghost tables, issue only affects when viewing email using **Microsoft Outlook**

Possible that fix removes necessary mso tags in `RockWeb/Scripts/summernote/plugins/RockPasteFromWord.js`

### Steps to Reproduce ###

1. Go to New Communication 
1. Send  new email 
1. Paste content from Paste From word function 
1. Send Email 
1. Open Email with Microsoft Office Outlook 
1. View MSO ghost table in email 

**Expected behavior:**

Email sent without ghost tables

**Actual behavior:**

Email contains the following information on random emails, not all emails 

```css
Normal 0 false false false EN-US X-NONE X-NONE /* Style Definitions */ table.MsoNormalTable {mso-style-name:"Table Normal"; mso-tstyle-rowband-size:0; mso-tstyle-colband-size:0; mso-style-noshow:yes; mso-style-priority:99; mso-style-parent:""; mso-padding-alt:0in 5.4pt 0in 5.4pt; mso-para-margin-top:0in; mso-para-margin-right:0in; mso-para-margin-bottom:8.0pt; mso-para-margin-left:0in; line-height:107%; mso-pagination:widow-orphan; font-size:11.0pt; font-family:"Calibri",sans-serif; mso-ascii-font-family:Calibri; mso-ascii-theme-font:minor-latin; mso-hansi-font-family:Calibri; mso-hansi-theme-font:minor-latin; mso-bidi-font-family:"Times New Roman"; mso-bidi-theme-font:minor-bidi;}
```

### Versions ###

* **Rock Version:** 13.7
